const utils = require('../../../../assets/utils');

describe(utils.suiteName(__filename), function() {
    utils.verifyRPCInterfaces('PhoneIoT', [
        ['getDevices', []],
        ['getColor', ['red', 'green', 'blue']],
        ['authenticate', ['device']],
        ['clearControls', ['device']],
        ['removeControl', ['device', 'id']],
        ['addImageDisplay', ['device', 'x', 'y', 'width', 'height', 'options']],
        ['addButton', ['device', 'x', 'y', 'width', 'height', 'options']],
        ['addJoystick', ['device', 'x', 'y', 'width', 'options']],
        ['addTextField', ['device', 'x', 'y', 'width', 'height', 'options']],
        ['addToggle', ['device', 'x', 'y', 'text', 'options']],
        ['addRadioButton', ['device', 'x', 'y', 'text', 'options']],
        ['addLabel', ['device', 'x', 'y', 'text', 'options']],
        ['listen', ['device']],
        ['getToggleState', ['device', 'id']],
        ['getJoystickVector', ['device', 'id']],
        ['getOrientation', ['device']],
        ['getCompassHeading', ['device']],
        ['getCompassDirection', ['device']],
        ['getCompassCardinalDirection', ['device']],
        ['getAccelerometer', ['device']],
        ['getFacingDirection', ['device']],
        ['getGravity', ['device']],
        ['getLinearAcceleration', ['device']],
        ['getGyroscope', ['device']],
        ['getRotation', ['device']],
        ['getGameRotation', ['device']],
        ['getMagneticFieldVector', ['device']],
        ['getMicrophoneLevel', ['device']],
        ['getLocation', ['device']],
        ['getProximity', ['device']],
        ['getBearing', ['device']],
        ['getAltitude', ['device']],
        ['getStepCount', ['device']],
        ['getLightLevel', ['device']],
        ['getImage', ['device', 'id']],
        ['setImage', ['device', 'id', 'img']],
        ['magnitude', ['vec']],
        ['normalize', ['vec']],
        ['setText', ['device', 'id', 'text']],
        ['getText', ['device', 'id']],
        ['setCredentials', ['device', 'password']],
    ]);
});
