// handles the incoming input arguments for the RPCs. Parses and validates the inputs based on the code docs for the functions

const GENERIC_ERROR = ''; // don't add to the error msg generated by rpc-manager
const types = {
    'Number': input => {
        input = parseFloat(input);
        if (isNaN(input)) {
            throw GENERIC_ERROR;
        }
        return input;
    },

    'Date': input => {
        input = new Date(input);
        if (isNaN(input.valueOf())) {
            throw GENERIC_ERROR;
        }
        return input;
    },

    'Array': input => {
        if (!Array.isArray(input)) throw GENERIC_ERROR;
        return input;
    },

    'Latitude': input => {
        input = parseFloat(input);
        if (isNaN(input)) {
            throw GENERIC_ERROR;
        } else if (input < -90 || input > 90) {
            throw 'Latitude must be between -90 and 90.';
        }
        return input;
    },

    'Longitude': input => {
        input = parseFloat(input);
        if (isNaN(input)) {
            throw GENERIC_ERROR;
        } else if (input < -180 || input > 180) {
            throw 'Longitude must be between -180 and 180.';
        }
        return input;
    },
};

module.exports = types;
