---
version: "3"
services:
  cloud:  # Basic account management, network overlay, etc
    restart: always
    image: netsblox/cloud:nightly
    environment:
        - "RUN_MODE=local"
    network_mode: host
    depends_on:
        - mongo
        - minio
    volumes:
       - "${PWD}/cloud/crates/cloud/config/:/config/"

  services:  # NetsBlox RPCs
    restart: always
    image: netsblox/services:nightly
    ports:
        - "8080:8080"
        - "1975:1975/udp" # Port for IotScape
        - "1975:1975/tcp" # Port for IotScape
    environment:
        - "NETSBLOX_CLOUD=http://172.17.0.1:7777"
        - "NETSBLOX_CLOUD_ID=LocalServices"
        - "NETSBLOX_CLOUD_SECRET=SuperSecret"
        - "MONGO_URI=mongodb://mongo:27017?directConnection=true"
        - "IOTSCAPE_SERVER=http://localhost"
        - "IOTSCAPE_PORT=1975"
    depends_on:
        - cloud

    volumes:
       - "${PWD}/services/src:/netsblox/src"

  browser:  # Hosts the client files
    restart: always
    image: netsblox/browser:nightly
    ports:
        - "8000:8000"
    environment:
        - "CLOUD_URL=http://localhost:7777"
        - "PORT=8000"
        - "ENV=dev"
    volumes:
       - "${PWD}/browser/:/usr/src/browser/"
    depends_on:
        - cloud

  mongo:  # Database for users, groups, project metadata, etc
    restart: always
    image: mongo:8.2-noble
    command: ["--replSet", "rs0", "--bind_ip_all", "--port", "27017"]
    ports:
       - "27017:27017"
    volumes:
       - mongodb_data:/data/db
       
  minio:  # Blob storage for project contents (media, etc)
    restart: always
    image: minio/minio:RELEASE.2022-11-11T03-44-20Z
    command: server /mnt/data --address :9000 --console-address :9001
    ports:
        - "9000:9000"
        - "9001:9001"
    environment:
        - "MINIO_ROOT_USER=KEY"
        - "MINIO_ROOT_PASSWORD=MYSECRET"
    volumes:
        - s3_data:/mnt/data

volumes:
  s3_data:
  mongodb_data:
