const FILE_HEADER_SIZE = 24;
const RADAR_DATA_SIZE = 2432;
const CTM_HEADER_SIZE = 12;
const MESSAGE_HEADER_SIZE = 28;

module.exports = {
	FILE_HEADER_SIZE, RADAR_DATA_SIZE, CTM_HEADER_SIZE, MESSAGE_HEADER_SIZE,
};
