module.exports = [
    ['United Arab Emirates Dirham','AED'],
    ['Afghan Afghani','AFN'],
    ['Albanian Lek','ALL'],
    ['Armenian Dram','AMD'],
    ['Netherlands Antillean Guilder','ANG'],
    ['Angolan Kwanza','AOA'],
    ['Argentine Peso','ARS'],
    ['Australian Dollar','AUD'],
    ['Aruban Florin','AWG'],
    ['Azerbaijani Manat','AZN'],
    ['Bosnia-Herzegovina Convertible Mark','BAM'],
    ['Barbadian Dollar','BBD'],
    ['Bangladeshi Taka','BDT'],
    ['Bulgarian Lev', 'BGN'],
    ['Bahraini Dinar', 'BHD'],
    ['Burundian Franc', 'BIF'],
    ['Bermudan Dollar', 'BMD'],
    ['Brunei Dollar', 'BND'],
    ['Bolivian Boliviano', 'BOB'],
    ['Brazilian Real', 'BRL'],
    ['Bahamian Dollar','BSD'],
    ['Bhutanese Ngultrum','BTN'],
    ['Botswanan Pula','BWP'],
    ['Belize Dollar','BZD'],
    ['Canadian Dollar','CAD'],
    ['Congolese Franc','CDF'],
    ['Swiss Franc','CHF'],
    ['Chilean Unit of Account UF','CLF'],
    ['Chilean Peso','CLP'],
    ['Chinese Yuan Offshore','CNH'],
    ['Chinese Yuan','CNY'],
    ['Colombian Peso','COP'],
    ['Cuban Peso','CUP'],
    ['Cape Verdean Escudo','CVE'],
    ['Czech Republic Koruna','CZK'],
    ['Djiboutian Franc','DJF'],
    ['Danish Krone','DKK'],
    ['Dominican Peso','DOP'],
    ['Algerian Dinar','DZD'],
    ['Egyptian Pound','EGP'],
    ['Eritrean Nakfa','ERN'],
    ['Ethiopian Birr','ETB'],
    ['Euro','EUR'],
    ['Fijian Dollar','FJD'],
    ['Falkland Islands Pound','FKP'],
    ['British Pound Sterling','GBP'],
    ['Georgian Lari','GEL'],
    ['Ghanaian Cedi','GHS'],
    ['Gibraltar Pound','GIP'],
    ['Gambian Dalasi','GMD'],
    ['Guinean Franc','GNF'],
    ['Guatemalan Quetzal','GTQ'],
    ['Guyanaese Dollar','GYD'],
    ['Hong Kong Dollar','HKD'],
    ['Honduran Lempira','HNL'],
    ['Croatian Kuna','HRK'],
    ['Haitian Gourde','HTG'],
    ['Hungarian Forint','HUF'],
    ['Internet Computer','ICP'],
    ['Indonesian Rupiah','IDR'],
    ['Israeli New Sheqel','ILS'],
    ['Indian Rupee','INR'],
    ['Iraqi Dinar','IQD'],
    ['Iranian Rial','IRR'],
    ['Icelandic Krona','ISK'],
    ['Jersey Pound','JEP'],
    ['Jamaican Dollar','JMD'],
    ['Jordanian Dinar','JOD'],
    ['Japanese Yen','JPY'],
    ['Kenyan Shilling','KES'],
    ['Kyrgystani Som','KGS'],
    ['Cambodian Riel','KHR'],
    ['Comorian Franc','KMF'],
    ['North Korean Won','KPW'],
    ['South Korean Won','KRW'],
    ['Kuwaiti Dinar','KWD'],
    ['Cayman Islands Dollar','KYD'],
    ['Kazakhstani Tenge','KZT'],
    ['Laotian Kip','LAK'],
    ['Lebanese Pound','LBP'],
    ['Sri Lankan Rupee','LKR'],
    ['Liberian Dollar','LRD'],
    ['Lesotho Loti','LSL'],
    ['Libyan Dinar','LYD'],
    ['Moroccan Dirham','MAD'],
    ['Moldovan Leu','MDL'],
    ['Malagasy Ariary','MGA'],
    ['Macedonian Denar','MKD'],
    ['Myanma Kyat','MMK'],
    ['Mongolian Tugrik','MNT'],
    ['Macanese Pataca','MOP'],
    ['Mauritanian Ouguiya (pre-2018)','MRO'],
    ['Mauritanian Ouguiya','MRU'],
    ['Mauritian Rupee','MUR'],
    ['Maldivian Rufiyaa','MVR'],
    ['Malawian Kwacha','MWK'],
    ['Mexican Peso','MXN'],
    ['Malaysian Ringgit','MYR'],
    ['Mozambican Metical','MZN'],
    ['Namibian Dollar','NAD'],
    ['Nigerian Naira','NGN'],
    ['Norwegian Krone','NOK'],
    ['Nepalese Rupee','NPR'],
    ['New Zealand Dollar','NZD'],
    ['Omani Rial','OMR'],
    ['Panamanian Balboa','PAB'],
    ['Peruvian Nuevo Sol','PEN'],
    ['Papua New Guinean Kina', 'PGK'],
    ['Philippine Peso','PHP'],
    ['Pakistani Rupee','PKR'],
    ['Polish Zloty','PLN'],
    ['Paraguayan Guarani','PYG'],
    ['Qatari Rial','QAR'],
    ['Romanian Leu','RON'],
    ['Serbian Dinar','RSD'],
    ['Russian Ruble','RUB'],
    ['Old Russian Ruble','RUR'],
    ['Rwandan Franc','RWF'],
    ['Saudi Riyal','SAR'],
    ['Solomon Islands Dollar','SBDf'],
    ['Seychellois Rupee','SCR'],
    ['Sudanese Pound','SDG'],
    ['Special Drawing Rights','SDR'],
    ['Swedish Krona','SEK'],
    ['Singapore Dollar','SDG'],
    ['Saint Helena Pound', 'SHP'],
    ['Sierra Leonean Leone','SLL'],
    ['Somali Shilling','SOS'],
    ['Surinamese Dollar','SRD'],
    ['Syrian Pound','SYP'],
    ['Swazi Lilangeni','SZL'],
    ['Thai Baht','THB'],
    ['Tajikistani Somoni','TJS'],
    ['Turkmenistani Manat','TMT'],
    ['Tunisian Dinar','TND'],
    ['Tongan Pa\'anga','TOP'],
    ['Turkish Lira','TRY'],
    ['Trinidad and Tobago Dollar','TTD'],
    ['New Taiwan Dollar','TWD'],
    ['Tanzanian Shilling','TZS'],
    ['Ukrainian Hryvnia','UAH'],
    ['Ugandan Shilling','UGX'],
    ['United States Dollar','USD'],
    ['Uruguayan Peso','UYU'],
    ['Uzbekistan Som', 'UZS'],
    ['Vietnamese Dong','VND'],
    ['Vanuatu Vatu','VUV'],
    ['Samoan Tala','WST'],
    ['CFA Franc BEAC','XAF'],
    ['East Caribbean Dollar','XCD'],
    ['Special Drawing Rights','XDR'],
    ['CFA Franc BCEAO','XOF'],
    ['CFP Franc','XPF'],
    ['Yemeni Rial','YER'],
    ['South African Rand','ZAR'],
    ['Zambian Kwacha','ZMW'],
    ['Zimbabwean Dollar','ZWL'],
];
