module.exports = [
    'Africa',
    'Albania',
    'Argentina',
    'Asia',
    'Austria',
    'Bahrain',
    'Belgium',
    'Bolivia',
    'Brazil',
    'Bulgaria',
    'Canada',
    'Cayman Islands',
    'Chile',
    'Colombia',
    'Croatia',
    'Czechia',
    'Denmark',
    'Ecuador',
    'England',
    'Estonia',
    'Europe',
    'European Union',
    'Faeroe Islands',
    'Finland',
    'France',
    'Germany',
    'Gibraltar',
    'Greece',
    'Hong Kong',
    'Hungary',
    'Iceland',
    'India',
    'Indonesia',
    'Ireland',
    'Isle of Man',
    'Israel',
    'Italy',
    'Japan',
    'Latvia',
    'Lebanon',
    'lithuania',
    'Luxembourg',
    'Malta',
    'Mexico',
    'Montenegro',
    'Morocco',
    'North America',
    'Northern Ireland',
    'Norway',
    'Oman',
    'Panama',
    'Peru',
    'Poland',
    'Romania',
    'Russia',
    'San Marino',
    'Scotland',
    'Serbia',
    'Seychelles',
    'Singapore',
    'Slovakia',
    'South Africa',
    'South Korea',
    'Spain',
    'Sweden',
    'Switzerland',
    'Turkey',
    'United Arab Emirates',
    'United Kingdom',
    'United States',
    'Uruguay',
    'Wales',
    'World'
    ];